client: Added support to override system capabilities
lldpd/lldpd pull request #526
Opened 2022-08-01 17:29 UTC by igsanchez

Patch in response to [#522](https://github.com/lldpd/lldpd/issues/522#issuecomment-1195935521)

1) configure system capabilities enabled <capability_0,capability_1,...>

    Override system capabilities with the provided value instead of using kernel information. Several capabilities can be specified separated by commas. Only available capabilities can be enabled. Valid capabilities are:

        other
        repeater
        bridge
        wlan
        router
        telephone
        docsis
        station

    Here is an example of use:

        lldpcli configure system capabilities enabled bridge,router

2) unconfigure system capabilities enabled

    Do not override capabilities and use the kernel information. This option undoes the previous one.

Ignacio Sanchez Navarro (Ignacio.Sanchez@uws.ac.uk) - University of the West of Scotland - Supported by H2020-ICT-2020-2/101017226 6G-BRAINS

-------------------------------------------------------------------------------
Modified files

lldpd-structs.h
    - Added new attribute "c_cap_override" to "lldpd_config" struct

conf-system.c
    - Added new function "cmd_capability" for new command to override the chassis capabilities
    - Added new function "register_commands_capabilities" to registers new commands to override the chassis capabilities
    - Added call to "register_commands_capabilities" in "register_commands_configure_system"

chassis.c
    - Added new function "_lldpctl_atom_st_int_chassis" to set "int" type vars in chassis
    - Added assignation of ".set_int" function in "chassis" var build

config.c
    - Added case for "lldpctl_k_config_chassis_cap_override" to get value of "c_cap_override" in "_lldpctl_atom_get_int_config" function
    - Added case for "lldpctl_k_config_chassis_cap_override" to set value of "c_cap_override" in "_lldpctl_atom_set_int_config" function

client.c
    - Added changes check for "c_cap_override" var in "client_handle_set_configuration" function
    - Added changes check for "c_cap_enabled" var in "client_handle_set_local_chassis" function

lldpctl.h
    - Added new enum values un "lldpctl_key_t" enum : "lldpctl_k_chassis_cap_enabled" and "lldpctl_k_config_chassis_cap_override"
    - Corrected some typos in previous comments

lldpd.c
    - Added check of capabilities override before setting new values in "lldpd_update_localchassis" function
    - Added check of capabilities override before setting initial value of "c_cap_enabled" to 0 in "lldpd_loop" function
    - Added initial set of "cfg->g_config.c_cap_override" to 0 in "lldpd_main" function

interfaces.c
    - Added check of capabilities override before setting new values in "interfaces_helper_chassis" function

display.c
    - Added new line to display the status of capabilities override in "show configration" command

lldpcli.8.in
    - Added new commands and descriptions to man file

2022-08-03 08:40 UTC, vincentbernat commented
Hey! Thanks! I have not looked at the code yet. Do you think you could add tests ? If you can't run them locally, you can add as many commits as you want on this PR, we will squash them later.

2022-08-03 11:24 UTC, igsanchez commented
Hello Vincent, 

Where would you suggest to add these test? I mean, as C checks in "lldpd/tests" or as python tests in "lldpd/tests/integration".

Cheers,
Ignacio

2022-08-03 12:05 UTC, vincentbernat commented
I meant as a Python test in `lldpd/tests/integration`. A single test which configures/unconfigures should be enough!

2022-08-05 11:11 UTC, igsanchez commented
Hello Vincent,

I have seen the test is failing, but it shouldn't. I have tested it locally and it passed. I have followed the instructions described in lldpd/tests/integration/README.md file.

Cheers,
Ignacio

2022-08-05 12:55 UTC, vincentbernat commented
I'll debug it for you, no worries.

2022-08-10 08:59 UTC, vincentbernat commented on src/client/conf-system.c
> +				return 0;
You need to free `config` as well.

2022-08-10 08:59 UTC, vincentbernat commented on src/client/conf-system.c
> +				return 0;
Free `config` as well.

2022-08-10 08:59 UTC, vincentbernat commented on src/client/conf-system.c
> +				return 0;
Free `chassis` as well.

2022-08-10 09:01 UTC, vincentbernat commented on src/lib/lldpctl.h
> +	lldpctl_k_config_chassis_cap_override, /**< `(I,WO)` Override chassis capabilities */
You need to move it to the end of the block. Otherwise, it would break existing clients.

2022-08-10 09:04 UTC, vincentbernat requested changes
I have added a commit to switch from space to tab (lldpd code base is using tabs for indentation). There is also a few things to change at first glance. I'll look into the problem around the functional test a bit later.

2022-08-10 09:27 UTC, vincentbernat commented
The tests are fixed with [5914eb4](https://github.com/lldpd/lldpd/pull/526/commits/5914eb4d68c73865bfd8b2e288b2b68edd799cbc). Feel free to fix the remaining bits by adding more commits and I'll squash everything into the first commit.

2022-08-11 09:28 UTC, igsanchez commented
Hello Vincent,

I have seen that you have fixed the few things you proposed. I couldn't make it yesterday. If there is anything else that I could do, just let me know.

Cheers,
Ignacio

2022-08-11 10:27 UTC, vincentbernat commented
Sorry for not waiting for you, there was something I wanted to debug, but I lost myself in something else. All good for me. I'll merge shortly.

Thanks!

2022-08-11 10:30 UTC, merged

2022-08-11 10:35 UTC, vincentbernat commented
I have tried to squash locally and merge in the interface to keep proper ownership to you, but GitHub is now confused. I have added your name to the NEWS entry. I hope that's OK for you.

2022-08-11 10:50 UTC, igsanchez commented
Ok, Thanks Vincent!!

2022-10-11 09:16 UTC, igsanchez commented
Hello Vincent,

Where would you suggest to add these test? I mean, as C checks in
"lldpd/tests" or as python tests in "lldpd/tests/integration"

Cheers,
Ignacio

On Wed, 3 Aug 2022 at 09:41, Vincent Bernat ***@***.***>
wrote:

> Hey! Thanks! I have not looked at the code yet. Do you think you could add
> tests ? If you can't run them locally, you can add as many commits as you
> want on this PR, we will squash them later.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lldpd/lldpd/pull/526#issuecomment-1203658040>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGFONJPFVXQRFIRUHENTAALVXIWCPANCNFSM55IJ6PLQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>